### ISSUE TITLE
Extract updated kernel configuration after olddefconfig

### ISSUE THREAD

**Issue by emkll** [freedomofpress/kernel-builder#12]
Currently the script will run `make olddefconfig` on the appropriate kernel config provided in the `configs` folder. Because we would like to commit to version control the exact config that is shipping in built kernels, we can add a step during the build process to copy the config of the build kernel into the `configs` folder to allow a developer to easily commit the config to version control after the kernel was built (and avoid the manual step to fetching the configuration, either by booting into the kernel or inspecting the source tarball produced by the build)

**Comment by legoktm** [comment]
> Because we would like to commit to version control the exact config that is shipping in built kernels

This is no longer really a goal for us. If someone wants to look at the exact config they can boot it and look at it or extract it from the package.
